# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Publish release

on:
  push:
    tags:
      - "*"

jobs:
  publish-release:
    name: Publish release
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - name: Setup .NET
        uses: actions/setup-dotnet@aa983c550dfda0d1722b6ac6aed55724ffacc6d3 # v3.1.0
        with:
          dotnet-version: 7.0.x
      - name: Checkout repo
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2
      - name: Build
        run: dotnet build -c Release
      - name: Publish release
        uses: notpeelz/action-gh-create-release@8222c48c6b66a5c4e64be89d535673bff358bcae # v3.0.0
        with:
          tag: ${{ github.ref_name }}
          title: ${{ github.ref_name }}
      - name: Publish NuGet package
        run: |
          for pkg in ./VersionInfoGenerator/bin/Release/*.nupkg; do
            dotnet nuget push "$pkg" \
              --api-key "${{ secrets.NUGET_TOKEN }}" \
              --source https://api.nuget.org/v3/index.json
          done
