# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Publish release

on:
  push:
    tags:
      - "*"

jobs:
  publish-release:
    name: Publish release
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - name: Setup .NET
        uses: actions/setup-dotnet@607fce577a46308457984d59e4954e075820f10a # v3.0.3
        with:
          dotnet-version: 7.0.x
      - name: Checkout repo
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2
        with:
          ref: ${{ github.sha }}
      - name: Build
        run: dotnet build -c Release
      - name: Publish release
        uses: notpeelz/action-gh-create-release@a3caaff31cdf1022430c5a95689330ed83de62f2 # v1.0.2
        with:
          token: ${{ github.token }}
          tag: ${{ github.ref }}
          title: "v${{ github.ref_name }}"
          files: |
            VersionInfoGenerator/bin/Release/*.nupkg
