# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Publish release

on:
  push:
    tags:
      - "*"

jobs:
  publish-release:
    name: Publish release
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - name: Setup .NET
        uses: actions/setup-dotnet@4d6c8fcf3c8f7a60068d26b594648e99df24cee3 # v4.0.0
        with:
          dotnet-version: 7.0.x
      - name: Checkout repo
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4
      - name: Build
        run: dotnet build -c Release
      - name: Publish release
        uses: notpeelz/action-gh-create-release@c1bebd17c8a128e8db4165a68be4dc4e3f106ff1 # v5.0.1
        with:
          tag: ${{ github.ref_name }}
          title: ${{ github.ref_name }}
      - name: Publish NuGet package
        run: |
          for pkg in ./VersionInfoGenerator/bin/Release/*.nupkg; do
            dotnet nuget push "$pkg" \
              --api-key "${{ secrets.NUGET_TOKEN }}" \
              --source https://api.nuget.org/v3/index.json
          done
