# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Publish release

on:
  push:
    tags:
      - "*"

jobs:
  publish-release:
    name: Publish release
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - name: Setup .NET
        uses: actions/setup-dotnet@67a3573c9a986a3f9c594539f4ab511d57bb3ce9 # v4.3.1
        with:
          dotnet-version: 9
      - name: Checkout repo
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Build
        run: dotnet build -c Release
      - name: Publish release
        uses: notpeelz/action-gh-create-release@c1bebd17c8a128e8db4165a68be4dc4e3f106ff1 # v5.0.1
        with:
          strategy: use-existing-tag
          tag: ${{ github.ref_name }}
          title: ${{ github.ref_name }}
      - name: Publish NuGet package
        run: |
          for pkg in ./VersionInfoGenerator/bin/Release/*.nupkg; do
            dotnet nuget push "$pkg" \
              --api-key "${{ secrets.NUGET_TOKEN }}" \
              --source https://api.nuget.org/v3/index.json
          done
